"""Criando tabelas iniciais

Revision ID: fdd76123a2d1
Revises: 
Create Date: 2026-09-01 22:15:24.173784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd76123a2d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_servico',
    sa.Column('id_servico', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('nivel_prioridade', sa.Enum('baixo', 'medio', 'alto', name='prioridade'), nullable=False),
    sa.PrimaryKeyConstraint('id_servico')
    )
    op.create_table('usuario_empresa',
    sa.Column('id_usuario', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ativo',
    sa.Column('id_ativo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('marca_modelo', sa.String(), nullable=True),
    sa.Column('numero_serie', sa.String(), nullable=True),
    sa.Column('id_usuario', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario_empresa.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_ativo'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('ordem_servico',
    sa.Column('id_ordem_servico', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('prioridade', sa.String(), nullable=True),
    sa.Column('id_usuario', sa.String(), nullable=False),
    sa.Column('id_ativo', sa.String(), nullable=False),
    sa.Column('id_servico', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_ativo'], ['ativo.id_ativo'], ),
    sa.ForeignKeyConstraint(['id_servico'], ['tipo_servico.id_servico'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario_empresa.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_ordem_servico')
    )
    op.create_table('agendamento',
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('id_agendamento', sa.String(), nullable=False),
    sa.Column('data_agendamento', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id_ordem_servico', sa.String(), nullable=False),
    sa.Column('id_usuario', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_ordem_servico'], ['ordem_servico.id_ordem_servico'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario_empresa.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_agendamento')
    )
    op.create_table('historico',
    sa.Column('id_historico', sa.String(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('acao', sa.String(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('condicionamento', sa.String(), nullable=True),
    sa.Column('id_ordem_servico', sa.String(), nullable=False),
    sa.Column('id_usuario', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_ordem_servico'], ['ordem_servico.id_ordem_servico'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario_empresa.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_historico')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico')
    op.drop_table('agendamento')
    op.drop_table('ordem_servico')
    op.drop_table('ativo')
    op.drop_table('usuario_empresa')
    op.drop_table('tipo_servico')
    # ### end Alembic commands ###
